[package]
name = "jupiter"
version = "0.1.1"
description = "Created with IDLGen"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jupiter"

[features]
rpc = []
i11n = ["anchor-i11n"]
cpi = []
events = []
default = ["rpc", "i11n", "cpi", "events"]

[dependencies]
anchor-lang = "0.30.0"
anchor-i11n = { optional = true, version = "0.1.0"}