[package]
name = "jupiter"
version = "0.1.1"
description = "Created with Anchor-IDLGen"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jupiter"

[dependencies]
anchor-lang = "0.29.0"
anchor-i11n = { git = "https://github.com/deanmlittle/anchor-i11n.git" }