[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.26"

[features]
resolution = true
skip-lint = false

[programs.localnet]
quartz = "6JjHXLheGSNvvexgzMthEcgjkcirDrGduc3HAKB2P1v2"

[programs.devnet]
quartz = "6JjHXLheGSNvvexgzMthEcgjkcirDrGduc3HAKB2P1v2"

[programs.mainnet]
quartz = "6JjHXLheGSNvvexgzMthEcgjkcirDrGduc3HAKB2P1v2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
buffer_authority = "./target/deploy/recover.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/$TEST_FILE"

[test]
startup_wait = 5000
