[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
funds_program = "6JjHXLheGSNvvexgzMthEcgjkcirDrGduc3HAKB2P1v2"

[programs.devnet]
funds_program = "6JjHXLheGSNvvexgzMthEcgjkcirDrGduc3HAKB2P1v2"

[programs.mainnet]
funds_program = "6JjHXLheGSNvvexgzMthEcgjkcirDrGduc3HAKB2P1v2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
buffer_authority = "./target/deploy/recover.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/$TEST_FILE"

[test]
startup_wait = 5000
