[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
funds_program = "B6gXhjcwsD8uFsaaPNFxeswxSNM79iP5mPgBnmxQJjn2"

[programs.devnet]
funds_program = "B6gXhjcwsD8uFsaaPNFxeswxSNM79iP5mPgBnmxQJjn2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/diegogarcia/workspaces/Quartz/Products/quartz-app/funds-program/program_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/$TEST_FILE"

[test]
startup_wait = 5000