[package]
name = "drift-state"
version = "2.92.0"
description = "Created with IDLGen"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "drift_state"

[features]
rpc = []
no-entrypoint=[]
cpi = ["no-entrypoint"]
events = []
solana = []
default = ["rpc", "cpi", "events"]

[dependencies]
anchor-lang = "0.29.0"
solana-program = "1.16"
bytemuck = { version = "1.4.0" }
borsh = "0.10.3"